/*
 * BalloonMessageDialog.java
 *
 * Created on May 30, 2008, 8:53 PM
 */
package com.beepsoft.ptools;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Point;

/**
 *
 * @author  Heri
 */
public class BalloonMessageDialog extends javax.swing.JDialog {

  /** Creates new form BalloonMessageDialog */
  public BalloonMessageDialog(Frame parent, Point location,
          int width, int height, String message) {
    super(parent, false);
    initComponents();
    if (location == null) {
      BspUtility.centerToScreen(this, parent);
    } else {
      setLocation(location);
    }
    setSize(width, height);
    message_area.setText(message);
    setVisible(true);
  }

  /** Creates new form BalloonMessageDialog */
  public BalloonMessageDialog(Dialog parent, Point location,
          int width, int height, String message) {
    super(parent, false);
    initComponents();
    if (location == null) {
      BspUtility.centerToScreen(this, parent);
    } else {
      setLocation(location);
    }
    setSize(width, height);
    message_area.setText(message);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    message_scroll = new javax.swing.JScrollPane();
    message_area = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);
    setUndecorated(true);
    getContentPane().setLayout(new java.awt.GridLayout(1, 0));

    message_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    message_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    message_area.setBackground(new java.awt.Color(255, 255, 220));
    message_area.setColumns(20);
    message_area.setEditable(false);
    message_area.setRows(5);
    message_area.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    message_area.setFocusable(false);
    message_area.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        message_areaMouseReleased(evt);
      }
    });
    message_scroll.setViewportView(message_area);

    getContentPane().add(message_scroll);

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void message_areaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_message_areaMouseReleased
  dispose();
}//GEN-LAST:event_message_areaMouseReleased


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea message_area;
  private javax.swing.JScrollPane message_scroll;
  // End of variables declaration//GEN-END:variables
}
