/*
 * BorderlessMessage.java
 *
 * Created on February 16, 2009, 9:08 PM
 */

package com.beepsoft.ptools;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyListener;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author  Heri
 */
public class BorderlessMessage extends javax.swing.JDialog {
    
    private BorderlessMessage me = this;
    private Timer tm;
    
    /** Creates new form BorderlessMessage */
    public BorderlessMessage(java.awt.Frame parent, boolean modal, String message, long delay, Component area) {
        super(parent, modal);
        initComponents();
        initializeDialog(parent, message, delay, area);
    }
    
    /** Creates new form BorderlessMessage */
    public BorderlessMessage(java.awt.Dialog parent, boolean modal, String message, long delay, Component area) {
        super(parent, modal);
        initComponents();
        initializeDialog(parent, message, delay, area);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    public BorderlessMessage(KeyListener aThis, boolean b, String saved, int i, Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        messagePanel.setBackground(new java.awt.Color(255, 255, 204));
        messagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        messagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                messagePanelMouseReleased(evt);
            }
        });
        messagePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                messagePanelKeyReleased(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        messageLabel.setText("Message");
        messageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                messageLabelMouseReleased(evt);
            }
        });
        messageLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                messageLabelKeyReleased(evt);
            }
        });
        messagePanel.add(messageLabel);

        getContentPane().add(messagePanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageLabelMouseReleased
        disposeDialog();
    }//GEN-LAST:event_messageLabelMouseReleased

    private void messagePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePanelMouseReleased
        disposeDialog();
    }//GEN-LAST:event_messagePanelMouseReleased

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        disposeDialog();
    }//GEN-LAST:event_formWindowDeactivated

    private void messageLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageLabelKeyReleased
        disposeDialog();
    }//GEN-LAST:event_messageLabelKeyReleased

    private void messagePanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messagePanelKeyReleased
        disposeDialog();
    }//GEN-LAST:event_messagePanelKeyReleased

    private void initializeDialog(java.awt.Window parent, String message, long delay, Component area) {
        setSize(400, 35);
        messageLabel.setText(message);
        if (area != null) {
            Point p = area.getLocationOnScreen();
            Dimension ad = area.getSize();
            Dimension d = getSize();
            int x = p.x + ad.width/2 - d.width/2;
            int y = p.y + ad.height/2 - d.height;
            setLocation(x, y-10);
        } else {
            BspUtility.centerToScreen(this, parent);
        }
        if (delay > 0) {
            TimerTask tt = new TimerTask() {
                @Override
                public void run() {
                    me.dispose();
                }
            };
            tm = new Timer();
            tm.schedule(tt, delay);
        }
        setVisible(true);
    }

    public void disposeDialog() {
        if (tm != null) {
            tm.cancel();
        }
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    // End of variables declaration//GEN-END:variables
    
}
