/*
 * BspProgressDialog2.java
 *
 * Created on January 18, 2008, 5:50 PM
 */

package com.beepsoft.ptools;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author  heri
 */
public class BspProgressDialog2 extends javax.swing.JDialog {
  
  /**
   * Creates new form BspProgressDialog2
   */
  public BspProgressDialog2(Window parent, String title) {
    super(parent);

    initComponents();

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = getSize();
    if (frameSize.height > screenSize.height) {
      frameSize.height = screenSize.height;
    } // - if
    if (frameSize.width > screenSize.width) {
      frameSize.width = screenSize.width;
    } // - if
    setLocation((screenSize.width - frameSize.width) / 2,
      (screenSize.height - frameSize.height) / 2 - 7);

    if (title != null) {
      setTitle(title);
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progress = new javax.swing.JProgressBar();
        progress2 = new javax.swing.JProgressBar();
        titleLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 140));
        progress.setStringPainted(true);

        progress2.setStringPainted(true);

        titleLabel.setText("Proses");

        titleLabel1.setText("Keseluruhan");

        titleLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        titleLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/beepsoft/ptools/corner.gif")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel1)
                    .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(titleLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(5, 5, 5)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(titleLabel1)
                .addGap(5, 5, 5)
                .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(titleLabel2))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

  public void setMaximum1(int max) {
    progress.setMaximum(max);
  }

  public void setMaximum2(int max) {
    progress2.setMaximum(max);
  }
  
  public void reset1() {
    progress.setValue(0);
  }
  
  public void reset2() {
    progress2.setValue(0);
  }
  
  public void increment1() {
    progress.setValue(progress.getValue() + 1);
  }
  
  public void increment2() {
    progress2.setValue(progress2.getValue() + 1);
  }
  
  public void setValue1(int i) {
    progress.setValue(i);
  }
  
  public void setValue2(int i) {
    progress2.setValue(i);
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    private javax.swing.JProgressBar progress2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    // End of variables declaration//GEN-END:variables
  
}
