/*
 * BspProgressDialog.java
 *
 * Created on January 18, 2008, 5:28 PM
 */

package com.beepsoft.ptools;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author  heri
 */
public class BspProgressDialog extends javax.swing.JDialog {
  
  /**
   * Creates new form BspProgressDialog
   */
  public BspProgressDialog(Window parent, String title) {
    super(parent);

    initComponents();

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = getSize();
    if (frameSize.height > screenSize.height) {
      frameSize.height = screenSize.height;
    } // - if
    if (frameSize.width > screenSize.width) {
      frameSize.width = screenSize.width;
    } // - if
    setLocation((screenSize.width - frameSize.width) / 2,
      (screenSize.height - frameSize.height) / 2 - 7);

    if (title != null) {
      setTitle(title);
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Progress");
        setMinimumSize(new java.awt.Dimension(180, 70));
        setModal(true);
        progress.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/beepsoft/ptools/corner.gif")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

  public void setMaximum(int max) {
    progress.setMaximum(max);
  }
  
  public void reset() {
    progress.setValue(0);
  }
  
  public void increment() {
    progress.setValue(progress.getValue() + 1);
  }
  
  public void setValue(int i) {
    progress.setValue(i);
  }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
  
}
